### PR TITLE
Reword account deletion messages

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd a few string replacements

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@caesar2164 can you post a screenshot and run it by Jen/courseops
so we can get signoff on text?

**Comment by caesar2164** [comment]
Screen Shot 2019-08-07 at 14 40 00

**Comment by stvstnfrd** [comment]
@caesar2164 This will need rebased over the new `hawthorn/wip`.

Maybe you can just recreate the branch and cherry-pick the commit?

**Review by stvstnfrd — CHANGES_REQUESTED** [review]
Can you rebase this?

**Comment by caesar2164** [comment]
there you go @stvstnfrd

**Review by stvstnfrd — APPROVED** [review]

**Comment by stvstnfrd** [comment]
cherry-picked.

**Pull request closed without merging**
